baseurl: "https://amarder.github.io/"
languageCode: "en-us"
title: "Andrew Marder"

author:
  Andrew:
    firstName: "Andrew"
    lastName: "Marder"
    twitter: "andrewmarder"

params:
  twitter:
    site: "andrewmarder"
    image: "/images/emacs.png"
